spring.application.name=turf-booking
server.port=8090

spring.datasource.url=jdbc:mysql://localhost:3306/turf_booking
spring.datasource.username=root
spring.datasource.password=vinjo@1234
spring.web.resources.static-locations=classpath:/static/

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true